// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hglyezkpcwxzihnkeuya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnbHllemtwY3d4emlobmtldXlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MTk2OTAsImV4cCI6MjA3MDk5NTY5MH0.XF3XYyBoj-_Z-6f3gRSwh1hYBEdXZkXOEvndfhQSC-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});